Interoperability between classic infrastructure and Libre-Mesh networks in Guifi.net
====================================================================================
:author: Gioacchino Mazzurco
:email: gio@eigenlab·org
:lang: en

:imgExt: {basebackend@docbook:300dpi.png:820px.png}

:MdHd: Modelo Híbrido
:SpNd: supernodo
:Nd: nodo

//== Introduction

The biggest community network in the world is Guifi.net <<ref:cnw>> it spreads across Catalonia and beyond. IP routing on a such big community network is not a trivial task, in addition to the big size, the decentralized nature of our network encourage choice, so usually different parts of our networks uses different routing protocols. +
In order to make those routing protocols interoperate is now mostly a manual job, various groups have developed several OpenWrt based solutions to ease networking equipment configuration, but seamless protocol interoperability is an open problem, moreover we work mostly with low cost embedded device, so little performance footprint is always a requirement. +
The scope of this work is to investigate mainly used routing protocols in particular BGP, BMX6 and BATMAN-adv, to study past interoperability experiments and to extend Libre-Mesh and possibly implementing seamless interoperability between it and Guifi.net. +
The new feature must be usable and stable so at the end of the project we can deploy it in our production setups such as Barcelona Botanical Garden, our offices in Aureasocial and others clients. +
Testing of the new features in real environment and protocols parameters adjusting for the optimal functioning is part of this work too.

== State of the art

=== BGP
BGP (acronym of Border Gateway Protocol) is a standard routing protocol designed to exchange routing and reachability information between autonomous systems (AS) on the Internet. BGP makes routing decisions based on paths, network policies, or rule-sets configured by a network administrator that is involved in making core routing decisions, because it needs information of each route reachability path to make decisions BGP is usually classified as a path vector protocol. Version 4 of BGP has been in use on the Internet since 1994, it's mayor improvement in respect to older version that are obsolete and unused on the Internet is the support for classless inter-domain routing (CIDR) and routes aggregation. +
BGP may be used for routing within an AS. In this application it is referred to as Internal BGP, or iBGP. In contrast, the Internet application of the protocol may be referred to as Exterior Border Gateway Protocol, External BGP, or eBGP. +
As BGP doesn't perform any type of neighbor discovery, peers are established by manual configuration. For each peer router a connection through TCP port 179 must be established, after the connection is established BGP daemons synchronize with peers by sending the whole routing information they have to peers, after this initial sync only updates are transmitted to peers.

=== Guifi.net
Guifi.net networks uses different routing protocols such as BGP, OSPF, OLSR, BMX6, BATMAN-adv, Babel and more.
Over time lot of Guifi.net nodes have been build sticking to the older but well known solution named _<<modelohibrido, {MdHd}>>_.
This solution imply lot of manual work and a central provisioning server that know all details about the Guifi.net network, de facto limiting the resilience,  the scalability and the growth of Guifi.net. To overcome _{MdHd}_ limitations lot of efforts developing new solutions have existed most of them based on mesh technology but none of them, mainly because of resource lack and consequent missing long term support, have been widely adopted causing even more fragmentation and making more difficult interoperability. Even if <<libre-mesh, Libre-Mesh>> has been bred independently, it is already used in some Guifi.net zones, but like other mesh based solution it is at moment used only for last mile distribution.

[[modelohibrido]]
==== {MdHd}
As of _{MdHd}_ community network nodes can belong to two categories: _{SpNd}s_ and _{Nd}s_, in this model _{Nd}s_ are not really nodes of the network as they do not do routing for other nodes of Guifi.net and just attach to a _{SpNd}s_, while _{SpNd}s_ do route <<ref:mdhdspnd>>. In _{SpNd}s_ usually a _Mikrotik routerboard_ is used as router while externals WiFi AP are configured as plain WDS bridge <<ref:mdhd>>, if two _{SpNd}s_ are connected by a WiFi link the router of each node see the router of the other node as if it was directly connected with an Ethernet cable. On top of the routers of each node BGP routing protocol is running, on each node connected BGP peering have to be established, each _{SpNd}_ has his own unique private ASN assigned by the Guifi.net Drupal based network map, in this setup each _{SpNd}_ of Guifi.net act as an AS with typical eBGP information exchange mode. +
While BPG seems the more appropriate routing protocol for a neutral internet exchange point, wireless community networks have completely different needs that BGP cannot satisfy such as chosing WiFi path with more bandwidth availabe or automatic link establishment. _{MdHd}_ has helped Guifi.net to grow but over time new technology better suited for wireless community have emerged exposing many limitations of this model.

=== BIRD
BIRD is an open source implementation of multiple Internet routing protocols in form of a daemon for Unix like systems. It is distributed under the GNU General Public License. BIRD supports IPv4 or IPv6 as separate daemons <<ref:birdipvx>>, multiple routing tables <<ref:birdmultitable>>, and BGP, RIP and OSPF routing protocols, as well as statically defined routes. Its design differs significantly from the better known routing daemons, GNU Zebra and Quagga <<ref:birdwikipedia>>. Currently BIRD is included in many Linux distributions <<ref:birdwikipedia>> in particular into OpenWrt <<ref:birdowrt>>. +

BIRD is used in several Internet exchanges as a route server <<ref:birdwikipedia>>, where it replaced Quagga because of its scalability issues <<ref:birdlinx>>.


=== BMX6
BMX6 is an open-source, mesh routing protocol, developed by Axel Neumann. It originated as an independent branch of the BATMAN routing protocol and is already used successfully in mesh networks <<ref:bmxan>>. Being a mesh routing protocol, BMX6 distributes node descriptions which can contain node-specific configurations. It optimizes the communication between neighboring nodes for minimal protocol overhead. From a routing protocol point of view BMX6 is classified as *table-driven proactive, distance vector* routing protocol so even if there is no traffic in the network, the routes to all the network nodes are known by all nodes <<ref:tablepro>>, while nodes does not have a global view of the network topology, so their knowledge is limited to next-hop to all destinations and the distance associated to it <<ref:distvect>>.

=== B.A.T.M.A.N. advanced
B.A.T.M.A.N. advanced (often referenced as batman-adv) is an implementation of the B.A.T.M.A.N. routing protocol in form of a Linux kernel module operating on layer 2. While usually wireless routing protocol implementations operates on L3 which means they exchange routing information by sending IP packets and bring their routing decision into effect by manipulating the kernel routing table. Batman-adv operates entirely on L2, not only the routing information is transported using raw Ethernet frames but also the data traffic is handled by batman-adv. It encapsulates and forwards all traffic until it reaches the destination, hence emulating a virtual network switch of all nodes participating. Therefore to the upper level all nodes appear to be link local and are unaware of the network's topology as well as unaffected by lower level network changes. Operating as a L2 routing protocol as there is no _L2 routing table_ to manipulate, data frames must be processed directly by batman-adv and doing it in user-space would be very inefficient, as for each packet processed it would be +read()+ and +write()+ to the kernel and back causing multiple context switching that are computationally intensive <<ref:contextswitch>>, which limits the sustainable bandwidth especially on low-end devices. To have good support for these devices as well and an overall good efficiency, batman-adv is implemented as a Linux kernel module. This way batman-adv avoid the context switching costs and only introduces a negligible packet processing overhead even under a high load. <<ref:batmanadv>>

=== qMp
qMp do facilitate the creation of roaming enabled mesh networks, it is based on OpenWrt and BMX6 <<ref:qmp>>, qMp already supports configuration provisioning by guifi.net map _unsolclick_ <<ref:missing>> for mesh parameters adjusting but it leave the interoperability with <<modelohibrido, {MdHd}>> mostly to manual static configuration done by the user <<ref:qmpmdhd>> or in rare cases to manually configured Quagga-BMX6 module that is unreliable, resource intensive and requires manual configuration. Moreover qMp is designed around BMX6, in a way that to add support for another routing protocol would imply a big refactoring of qMp code.

[[libre-mesh]]
=== Libre-Mesh
Libre-Mesh (often referenced as LiMe) is an initiative undertaken by community networks members of several continents that collaborate towards a common goal: to develop a set of tools that facilitate the deployment of Free Networks for any community in the world. +
Main tool is LiMe meta-firmware: based on OpenWrt, eases the creation of community networks, and enables existing communities to add roaming enabled network clouds to their networks. +
To accomplish his goal LiMe meta-firmware have an highly modular design and implementation, the core of LiMe meta-firmware is the lime-system package.

==== Network Architecture
TODO

==== Software Architecture
LiMe meta-firmware is structured as a set of OpenWrt packages, it provides a command line tool `lime-config` that when invoked simply delegate the work of updating the configurations to installed LiMe modules by calling their `clean()` and `configure()` methods, LiMe minimal installation already ships necessary modules but the architecture is meant to be extensible so more modules can be added if needed. LiMe modules are often modular themselves, an UML scheme may help the comprehension of LiMe architecture as a whole:

[[fig:lime-system_UML]]
.UML diagram of lime-system package.
image::images/lime-system_UML_{imgExt}[align="center"]

===== Hardware Detection
Hardware detection module is in charge of detecting hardware components of the router and if some of them need a special configuration in order to work according to LiMe needs generate that configuration, to accomplish its task as you cas see in <<fig:lime-system_UML>> it is modular itself and it's submodules are called +detectors+. For each +detector+ installed ( such as +lime-hwd-usbradio+ ) it execute the respective +clean()+ method that is supposed to cleanup outdated configuration and the +detect_hardware()+ method that is supposed to configure the hardware and can write specific +config+ sections in +/etc/config/lime+ to be read by others lime components if necessary.

===== Wireless
Wireless module detect WiFi interfaces and prepare them for usage with LiMe, to accomplish its task it reads and write to +/etc/config/lime+ and +/etc/config/wireless+, as depicted in <<fig:lime-system_UML>> it is modular itself and delegate part of the works to his submodules called +mode+. Each +mode+ must implement a method called +setup_radio(radio, args)+ that take as argument an +uci.wireless.radio+ table and optional adjuntive arguments and is in charge of configure the WiFi radio to operate as needed by LiMe.

===== Network
Network module is in charge of configuring network interfaces and routing protocols, it is a big task to accomplish in a nifty way to do it is modular too. It offers a tight API to his modules that are called +proto+ (such as +lime-proto-bgp+) while they must expose to network module a statefull interface that consists of:

- +configured+ flag, it is false by default and setted to true when the +proto+ is configured.
- +configure(args)+ this method is in charge of configuring the underlying routing protocol, args is an array containing all parameters found in configuration file, parameters have positional meaning.
- +setup_interface(ifname, args)+ this function is called once per each networking interface found on the router +ifname+ is the Linux name of the interface and +args+ is an array containing all related parameters found in configuration file.
- +apply()+ usually just restart the underlying routing daemon to make the new configurations effective.

===== Firewall
Configure OpenWrt firewall if installed or iptables and ebtables according to LiMe needs.

===== System
Configure system general settings like host-name and other miscellaneous stuff.

===== Hardware detector ground routing
Ground routing is a node setup similar to _{MdHd}_ in the sense of splitting routing and geographic linking task into different devices. In this setup a device running LiMe is in charge of routing while other devices justs deal with physic and link layer stuff. Those devices can keep their original fabric firmware, or being flashed with a plain OpenWrt image or even run a lite version of LiMe. The name ``ground routing'' came from the habit of routing enthusiasts, to keep the L1/L2 devices on which they do not usually change the configurations on the roof (necessary to have good WiFi links) while the ``ground router'', which is the subject of their experiments, is kept inside the house, ``on the ground'', so if the configuration changes accidentally disrupt connectivity to the router, physical access is simple and there is no need to access the roof for recovery. As this functionality is not needed in default setup +lime-hwd-ground-routing+ is distributed as a separate package and is not included in the default LiMe distribution.

.UML diagram of lime-hwd-ground-routing package.
image::images/lime-hwd-ground-routing_UML_{imgExt}[align="center"]

When invoked by +lime.hardware_detection+, +lime.hwd.ground_routing.clean()+ clean outdated ground routing sections, then +lime.hwd.ground_routing.detect_hardware()+ creates ground routing configuration sections that eventually can include 802.11q interfaces or hardware switch configurations <<ref:owrthwswitch>><<ref:owrtswitch>>, according to node owner needs and hardware capabilities. In contrast to _{MdHd}_ and Ninix.org _Routing a terra_ that are meant for a specific routing protocol (BGP the first <<ref:mdhd>>, and OLSR the latter <<ref:nnxgr>>) LiMe Ground Routing is routing protocol agnostic, thanks to the LiMe modular structure it is focused just on preparing the L1/L2 setup on the LiMe router and then the upper layer routing modules treat L2 interfaces created by Ground Routing the same as any other L2 interface <<ref:limegr>>. This permit to LiMe networks to use any routing protocol on top of a Ground Routing setup and not being limited to a specific routing protocol, thanks to this abstraction LiMe can also ``emulate'' Ninix.org _Routing a terra_ just installing both +lime-hwd-ground-routing+ and +lime-proto-olsr+, and Guifi.net _{MdHd}_ just installing both +lime-hwd-ground-routing+ and +lime-proto-bgp+ that is part of the work done during this internship.

===== Hardware detector OpenWrt wan
This hardware detector is shipped as an optional package +lime-hwd-openwrt-wan+, but is installed and enabled by the default in LiMe distribution.

.UML diagram of lime-hwd-openwrt-wan package.
image::images/lime-hwd-openwrt-wan_UML_{imgExt}[align="center"]

Low cost consumer hardware, that community networks often use, have multiple Ethernet ports, although from a technical point of view those Ethernet ports are pretty much equivalent each other, vendors usually present them as different to the end user, in particular there is usually a separated port labeled WAN end the other ports usually grouped together labeled LAN. The end user is told by the router vendor that the WAN port is meant to be connected to the Internet connection and the LAN ports to be connected to local computers. To avoid confusing the user this convention is usually respected both in OpenWrt and in LiMe, although because technically those ports are equivalents there is no automatic way to determine which port is WAN by software. OpenWrt developers when they add support and write the default configuration for a specific device they let the port labeled as WAN to auto-configure via DHCP while they configure as static the ones labeled as LAN by the vendor <<ref:owrtlanwan>>. LiMe does support almost every device that is well supported by OpenWrt so, instead of duplicating the work of determine if there is a WAN labeled port and which port is it, delegate this task to +lime-hwd-openwrt-wan+ that check which is the WAN port in the OpenWrt default configuration that is backed up into +/etc/lime/config.original/+ by LiMe at first boot <<ref:99limeconfig>> and configure it as needed by LiMe and to behave as user expect to.

.+lime.hwd.openwrt_wan.detect_hardware()+ snippet that retrieves WAN +ifname+.
[source, lua]
---------------------------------------------------------
local uci_o = libuci:cursor()
uci_o:set_confdir("/etc/lime/config.original")
uci_o:set_savedir("/dev/null")
local ifname = uci_o:get("network", "wan", "ifname")
---------------------------------------------------------

===== Hardware detector USB radio
This hardware detector is distributed as an optional package +lime-hwd-usbradio+, it is in charge of detecting WiFi USB radio.

.UML diagram of lime-hwd-usbradio package.
image::images/lime-hwd-usbradio_UML_{imgExt}[align="center"]

Most consumer routers features one or more USB ports, to setup print servers or share files from an attached disk. With OpenWrt those ports are usually usable as full USB  and not only for specific tasks. Taking advantage of this community networks activists started creating low cost multi-radio routers by plugging USB WiFi radios into those routers. Although OpenWrt configuration system doesn't recognize those USB radio automatically so the users had to configure them manually. To fill the gap between OpenWrt wireless configuration system and having USB radio automatically working +lime-hwd-usbradio+ has been developed. As OpenWrt is compatible with Hotplug system <<ref:owrthotplug>> when an USB radio is connected to the router an Hotplug event is fired <<ref:hotplug>>, +lime.hwd.usbradio+ catch that event trough a crafted Hotplug hook <<ref:usbradiohook>> and configure the USB radio taking in account his capabilities. In the log run the lack of good quality support for +adhoc+ or +ieee80211s+ WiFi modes in Linux drivers for USB radios especially for the cheaper ones has discouraged users to use them for mesh links. Currently USB radios detected by +lime-hwd-usbradio+ are mainly used in AP or STA WiFi modes.

===== Protocol adhoc
This protocol is shipped as part of +lime-system+ package as you can see in <<fig:lime-system_UML>> and it's enabled by default, it is charge of just generating the network configuration that bring up L2 interfaces corresponding to L1 radio interfaces configured as of _LiMe WiFi Mode_ +adhoc+.

===== Protocol anygw
This protocol is shipped as an optional package +lime-proto-anygw+, but is installed and enabled by the default in LiMe distribution.

.UML diagram of lime-proto-anygw package.
image::images/lime-proto-anygw_UML_{imgExt}[align="center"]

In WiFi networks usually when a client move and get far from the AP it is associated, if it sense better signal from another AP with the same SSID it is expected to automatically ->deassociate<- from the far node and associate to the near one. When during this process upper network layers, specifically the user, doesn't experience a connection interruption it is commonly referred as roaming <<ref:missing>>. LiMe mesh networks does supports roaming at L2. In L2 roaming scenarios because the clients are usually configured via DHCP and it operates at an higher layer then roaming the client keep using the same gateway of when it associated first time without caring of it's position, this behavior may cause client packets be routed in a suboptimal way, moreover if the client keep roaming far away from the initial gateway it may experience low network performances.

.Roaming without anygw.
image::images/suboptimal_roaming_{imgExt}[align="center"]

Legenda::
- Blue dashed lines: Mesh links
- Purple dot dashed line: Client packets routed at L3
- Green dot dashed line: Client packets routed at L2


To avoid this unwanted behavior +lime-proto-anygw+ offer a light implementation of anycast gateway. Anygw builds the virtual Ethernet interface +anygw+ on top of <<proto:lan, LAN protocol>> clients access interface +br-lan+ using the Linux kernel module +macvlan+ <<ref:macvlan>><<ref:linuxswitching>>. When anycast gateway is enabled the first address of the mesh network subnet is reserved for anycast gateway operation, together with the IP also a crafted locally administered but valid *unicast* <<ref:macaddress>> MAC address is used, all anycast gateways on a LiMe L2 cloud share the same IP and MAC address.

.+anygw+ addresses generation.
[source, lua]
---------------------------------------------
local ipv4, ipv6 = network.primary_address()

local anygw_mac = "aa:aa:aa:aa:aa:aa"
local anygw_ipv6 = ipv6:minhost()
local anygw_ipv4 = ipv4:minhost()
---------------------------------------------

In this way when a client sends a packets directed outside it's cloud it gets ``intercepted'' and optimally routed at L3 by the nearest router.

.Roaming with anygw.
image::images/anygw_roaming_{imgExt}[align="center"]


===== Protocol batadv
TODO

.UML diagram of package lime-proto-batadv.
image::images/lime-proto-batadv_UML_{imgExt}[align="center"]

===== Protocol BMX6
TODO

.UML diagram of package lime-proto-bmx6.
image::images/lime-proto-bmx6_UML_{imgExt}[align="center"]

===== Protocol ieee80211s
This protocol is shipped as part of +lime-system+ package as you can see in <<fig:lime-system_UML>> but it is not enabled by default, +lime.proto.ieee80211s+ is a relatively new born into LiMe family and the similarly used +lime.proto.adhoc+ is preferred as default configuration because it has been more tested and is well known to community networks activists. Similarly to his old brother +lime.proto.adhoc+, +lime.proto.ieee80211s+ is charge of just generating the network configuration that bring up L2 interfaces corresponding to L1 radio interfaces configured as of _LiMe WiFi Mode_ +ieee80211s+.

[[proto:lan]]
===== Protocol LAN
As you can see in <<fig:lime-system_UML>> +lime.proto.lan+ is shipped as part of +lime-system+ package. LiMe LAN protocol is  enabled by default and is meant to configure the network local to the node, in the default configuration it is also in charge of giving access to the mesh network at layer 2 to clients next to the node. It configure the node main IPv4 and IPv6 and bridge all network interface meant to give access to clients like wireless AP interfaces and Ethernet interfaces into +br-lan+.

===== WiFi mode adhoc
TODO

===== WiFi mode ap
TODO

===== WiFi mode ieee80211s
TODO

== Developed tools

=== lime-system

Even if LiMe is highly modular, to have a sane and modular itself BGP route exchange implementation required some modification to LiMe core, in particular the abstract class _Lime Routing Protocol_ has been extended by adding the +bgp_conf(...)+ method. A _Lime Routing Protocol_ which want to exchange routes with BGP should implement that method in a way that it does the necessary configuration of the +proto+ itself and returns to the caller a string containing a BIRD snippet configuration for route exchange with that +proto+.

.UML diagram of lime-system package, evidenced in green the developed parts.
image::images/lime-system_devel_UML_{imgExt}[align="center"]

Highlighted in green the parts modified in the scope of the internship.


==== Protocol LAN

As +lime.proto.lan+ does very minimal work at L3 it doesn't need much interaction with BGP to announce his subnet route. Implementing +lime.proto.lan.bgp_conf(...)+ has been quite simple as you can see in the following code snippet.

[source, lua]
------------------------------------------------------------
function lan.bgp_conf(templateVarsIPv4, templateVarsIPv6)
	local base_conf = [[
protocol direct {
	interface "br-lan";
}
]]
	return base_conf
end
------------------------------------------------------------

=== lime-proto-anygw
As the interaction of +lime.proto.anygw+ with +lime.proto.bgp+ is very similar to the one of +lime.proto.lan+, +lime.proto.anygw.bgp_conf(...)+ is just an adaptation of +lime.proto.lan.bgp_conf(...)+ as you can see in the following code snippet.

[source, lua]
------------------------------------------------------------
function anygw.bgp_conf(templateVarsIPv4, templateVarsIPv6)
	local base_conf = [[
protocol direct {
	interface "anygw";
}
]]
	return base_conf
end
------------------------------------------------------------

=== lime-proto-bgp
To accomplish the task of interoperability between Libre-Mesh networks and Guifi.net BGP infrastructure, I had to create a new `proto` for libre-mesh called `lime-proto-bgp`, it is in charge of configuring the LiMe system so it is capable of BGP routing, as back-end it uses BIRD.
While the module is in charge of configuring BGP routing it delegate through the LiMe modularization pattern to the others `proto` the specific configuration needed to make possible to automatize the interoperation between the specific `proto` and BGP, to accomplish that a new callback has been added to the standard `proto` API:

- `proto.bgp_conf(templateVarsIPv4, templateVarsIPv6)` it is called by the `proto` BGP for each `proto` the user has requested to exchange routes with, this function take as parameters two tables that are both readable to read already defined template variable and writable to eventually define additional template variables to pass back to `proto` BGP and returns a template snippet that is appended to the bird configuration file by `proto` BGP.

==== Exporting BGP routes to a kernel table

[source,bash]
--------------------------------------
table tobmx;

protocol pipe {
	table master;
	peer table tobmx;
	import all;
	export filter {
		if source = RTS_BGP then accept;
		else reject;
        };
}

protocol kernel
{
	scan time 20;
	table tobmx;
	kernel table 200;
	import all;
	export all;
}
--------------------------------------

==== Importing mesh routes with low preference
Guifi.net BGP routers are from different vendors and often they have different implementation on which route attributes are considered when deciding which path to prefer, after reading documentations from different vendors, seems to me that in eBGP setups (like Guifi.net) the most reliable way to share a route with low preference is to artificially enlarge it's AS path, this technique is called AS-path-prepending and it's common in situation where someone want to share a route but want others routers prefer other paths if there is some path available.
some references: +
http://wiki.nil.com/AS-path_prepending_%28technical_details%29 +
Check #bird 2015/08/19 IRC log for more details


[source,bash]
--------------------------------------
protocol bgp {
        local as 65000;                      # Use a private AS number
        neighbor 198.51.100.130 as 64496;    # Our neighbor ...
        multihop;                            # ... which is connected indirectly
        export filter {                      # We use non-trivial export rules
                if source = RTS_STATIC then { # Export only static routes
                        # Assign our community
                        bgp_community.add((65000,64501));
                        # Artificially increase path length
                        # by advertising local AS number twice
                        if bgp_path ~ [= 65000 =] then
                                bgp_path.prepend(65000);
                        accept;
                }
                reject;
        };
        import all;
        source address 198.51.100.14;   # Use a non-standard source address
}
--------------------------------------

==== BIRD: Interesting threads

- link:http://bird.network.cz/pipermail/bird-users/2012-February/002822.html[How redistribute routes from kernel table]
- link:http://bird.network.cz/pipermail/bird-users/2013-November/004051.html[Routes in kernel table not being imported]
- link:http://pastebin.ca/2986781[BIRD protocols default preferences]
- link:http://bird.network.cz/?get_doc&f=bird-3.html#ss3.3[BIRD protocol preference option]


=== lime-proto-bmx6
==== Importing BGP routes with low bandwidth

[source,bash]
--------------------------------------
config plugin 'table'
        option plugin 'bmx6_table.so'

config redistTable 'fromBird'      
        option redistTable 'fromBird'  
        option table '200'                        
        option bandwidth '100'     
        option all '1'                 
        option sys '12'
--------------------------------------


== Experimental results
TODO

=== Interoperability use-cases
Due to LiMe modular nature this development has many possible application that spread out of boundaries of this internship, in the following sections a brief analysis of more common use-cases on which the development has been focused is exposed.

[[meshdistribution]]
==== Mesh network as distribution
In this scenario a BGP backbone is used as transport network while the mesh network is used as last mile distribution.

TODO: Wifi mesh links shold be curvy in graphs

image::images/simple_exchange_topology_{imgExt}[align="center"]

Legenda::
- Black routers: Routers running LiMe with pure mesh setup.
- Red routers: Guifi.net routers configured as of _{MdHd}_.
- Blue straight lines: Cabled mesh links.
- Blue curvy dashed lines: WiFi mesh links.
- Yellow straight lines: Guifi.net links as of _{MdHd}_.

This use case is someway workable also with the pasts solution but with strong drawbacks:

- Instead of the ``red and black'' router we would need two devices one of the ``red type'' let's call it +R+ and one of the ``black type'' lets call it +B+ connected, this mean a frontier node cost the double on average.
- The +B+ router would announce statically the whole 10.0.0.0/8 to the mesh network and have +R+ as gateway for the entire 10.0.0.0/8 net, this causes packets generated into the mesh directed to nonexistent hosts in that range will flow all across the mesh and even get into the BGP backbone, effectively reducing bandwidth available for legitimate packets.
- In the +R+ router all the subnets used by the mesh network must be statically routed to +B+ router and then written into the BGP daemon configuration to be announced to the rest of the ``red network'', so each time a subnet is added to the the mesh network the +R+ router need to be reconfigured manually, consuming time of some skilled Guifi.net operator.

All those limitations are solved using the software developed during this internship, moreover other more complex and even more common interoperability scenarios gets solved.

==== Mesh network with multiple exchanges
This scenario is very common in high population density zones, small neighborhood community mesh network grow beyond the district boundaries gaining geographical proximity to multiple backbone nodes, as the number of user usually grow too as the network expand having just an exchange point become a bottleneck, in this case having multiple exchange point can improve the access bandwidth to upstream networks.

image::images/multiple_exchanges_topology_{imgExt}[align="center"]

This scenario in not practically manageable with past technology, the more exchange points are added the trickier it gets to manually write a configuration that works stably. During the internship an automatic solution has been developed although it hasn't been trivial, the usual Guifi.net eBGP setup is not enough as it causes routing loop <<ref:routeloop>> in this situation. When an host like +2001:DB8:9::4+ from the LiMe network send a packet to an host like +2001:DB8:1::3+ into BGP network the packet make his way to the destination without problems. Unfortunately is not the same when +2001:DB8:1::3+ send a packet to his friend +2001:DB8:9::4+. The packet is correctly routed toward the exchange +BGPx2+ but there because routes learned via BGP are preferred it's sent back to +BGP4+ expecting it have a better path for those packets. +BGP4+ again thinks that +BGPx2+ is the best next hop to reach +2001:DB8:9::4+ and forward the packet to +BGPx2+ and so on till the packet TTL is exhausted and one of the routers discard it.

image::images/multiple_exchanges_ebgp_loop_{imgExt}[align="center"]

Legenda::
- Directed black dashed line: packets flowing in the direction of the arrow.

But what in detail causes this unwanted behavior? We can find the answer is in +BGPx2+ routing table of which the relevant snippet is reported in the following lines.

---------------------------------------------------------------
2001:DB8:1::/64 via $BGP4 proto bird metric 0
2001:DB8:1::/64 dev bmxOut_BGPx1 proto static metric 1024
2001:DB8:9::/64 via 2001:DB8:8::1 proto bird metric 0
2001:DB8:9::/64 dev bmxOut_BMX1 proto static metric 1024
---------------------------------------------------------------

We can observe there are two routes towards +2001:DB8:9::/64+ one learned via BGP (the +proto bird+ ones) that have lower metric and one learned by BMX6 (the ones associated to +dev bmx*+) that have higher metric, thus the BIRD routes are always preferred. One could think that the problem could be fixed just by giving to BMX6 more preference but this tentative would just fail because it solves the loop in the BGP->BMX6 direction but it creates the exact opposite loop in BMX6->BGP direction. To solve this problem the classic way to solve this problem on BGP networks usually is adopt the iBGP setup. In a iBGP setup routers share the same ASN so the exchanges can recognize internal routes when they learn them form other eBGP routers and avoid adding them to the kernel routing table. To adopt iBGP solve the problem but with an unbearable cost for an auto-organized mesh network that is that each iBGP router must be configured to establish peering connections to each other router in a setup called _full-mesh_ where every router speaks to all other routers directly <<ref:wkpdbgp>>. At this point, no other solutions then iBGP has been found. I started investigating how iBGP works internally and I discovered that the _full-mesh_ peering is needed because every iBGP router need share the same routing information with all other iBGP routers <<ref:ebgpibgp>>. In our case as BMX6 is a proactive distance-vector routing daemon it already spreads all routes to all routes so I supposed that in our case the iBGP _full-mesh_ setup may be avoided, and empirical tests proved this supposition true. In fact loop is avoided and every host of both BGP and BMX6 networks can successfully reach every host of the whole Guifi.net (both BMX6 and BGP parts).

---------------------------------------------------------------
2001:DB8:1::/64 via $BGP4 proto bird metric 0
2001:DB8:1::/64 dev bmxOut_BGPx1 proto static metric 1024
2001:DB8:9::/64 dev bmxOut_BMX1 proto static metric 1024
---------------------------------------------------------------

==== Mesh network as transport
*TODO: Needs further analysis + control flow schema* +
The most important technical factor that slowed down LiMe adoption into Guifi.net is that the majority of preexistent network infrastructure is built following the _{MdHd}_ so when someone decide to extend Guifi.net infrastructure need to be compatible with _{MdHd}_, without the development done during this internship the only possible interoperability setup was having the mesh as a leaf <<meshdistribution, distribution network>>, while now it is possible to build Guifi.net backbone with LiMe being compatible both with mesh and BGP networks, it is even possible to use LiMe to fill the gap between isolated BGP network islands.

image::images/mesh_as_transport_topology_{imgExt}[align="center"]

This will certain encourage LiMe adoption and maybe finally obsolete _{MdHd}_, giving the possibility to Guifi.net to jump into another phase of horizontal growth with less dependency from manual configuration work, skilled people will have time to work on more interesting and not repetitive configuration tasks, with consequent work quality improvement, costs reduction and increased network accessibility for the masses.

==== Route count limitation

BMX6 store distribute routes in a shared structure called ``node description'' for performance reasons the size of this structure is limited and it's not enough to contain the whole Guifi.net BGP routing table, a first approach to resolve this problem was to enable route aggregation in BMX6 ``redistTable'' plug-in, but despite the high CPU usage the size of the table was reduced only by half and that was not enough to fit inside a ``node description'', moreover the high CPU load caused timeouts in communication between BMX6 and Linux kernel causing BMX6 to crash. To solve this problem next BMX6 version node description will be structured like a linked list so the node description can contain a pointer to another structure if just one is not enough to store all the needed informations, the draw back is that this is not compatible with past versions of BMX6 but it doesn't represents a blocking problem because BMX6 users are used too incompatible changes between versions, this solution has been discussed at BattlemeshV8 and we will do further testing at our offices in Barcelona.

==== Reducing the performance footprint
Default BMX6 `redistTable` configurations are not suitable to our needs in fact they make the router sloppy and with 100% CPU load every-time, doing some analysis on what was happening I found some causes:

- By default `redistTable` do routes aggregation that is a CPU and memory intensive work.
- It reacts to every single change in the routing table recalculating all aggregations.
- Our routing table is big so calculating the ``aggregated'' version is a long work.
- Our average device have quite limited resources (300-600Mhz MIPS CPU, 32-128MB RAM)

To solve this problem I have disabled route aggregation while enabling routing table event aggregation, with event aggregation it should be even possible to enable route aggregation but further studying it's needed, and the behavior of loop avoidance in case aggregation is enabled need to be studied too.


[source,lua]
---------------------------------------------------------
-- Disable route aggregation
uci:set("bmx6", "fromBird", "aggregatePrefixLen", "128")
-- Aggregate routing tables events by 60s time slots
uci:set("bmx6", "general", "redistTableDelay", "60000") 
---------------------------------------------------------


== Conclusions
TODO


== Appendix: Code
TODO

== Appendix: License
This work is licensed under the Creative Commons Attribution-ShareAlike 4.0 International License. +
To view a copy of this license, visit http://creativecommons.org/licenses/by-sa/4.0/. +
Copyright © 2015 {author}.

image::images/CC-by-sa_{imgExt}["License", align="left", link="http://creativecommons.org/licenses/by-sa/4.0/"]

// Specify the section template avoid "References" being threated as a special section title (see User Guide 5.4.1) that cause an xmllint error
[sect1]
== Glossary

include::glossary.asciidoc[]

// Specify the section template avoid "References" being threated as a special section title (see User Guide 5.4.1) that cause an xmllint error
[sect1]
== References

include::references.asciidoc[]
