Interoperability between Libre-Mesh and Guifi.net
=================================================
:author: Gioacchino Mazzurco
:email: gio·@·eigenlab·org

The biggest community network of the world is Guifi.net and it spreads across Catalonia and beyond. IP routing on a such big community network is not a trivial task, in addition to the big size, the decentralized nature of our network encourage choice, so usually differents parts of our networks uses differents routing protocols. +
In order to make those routing protocols interoperate is now mostly a manual job, various groups have developed several OpenWrt based solutions to ease networking equipment configuration, but seamless protocol interoperability is an open problem, moreover we work mostly with low cost embedded device, so little performance footprint is always a requirement. +
The scope of this work is to investigate mainly used routing protocols in particular BGP, Bmx6 and BATMAN-adv, to study past interoperability experiments and to extend Libre-Mesh implementing seamless interoperability it and Guifi.net. +
The new feature must be usable and stable so at the end of the project we can deploy it in our production setups such as Barcelona Botanical Garden, our offices in Aureasocial and others clients. +
Testing of the new features in real environment and protocols parameters adjusting for the optimal functioning is part of this work too.


== Guifi.net

Our networks uses differents routing protocols such as BGP, OSPF, OLSR, Bmx6, BATMAN-adv, Babel and more. +
Over time lot of guifi.net nodes have been builded following the <<ibridmodel, Ibrid Model>>

[[ibridmodel]]
=== Ibrid model

As of ibrid model community network nodes can belong to two categories: _supernodos_ and _nodos_, in this model _nodos_ are not really nodes of the network as they do no do routing for other nodes of guifi.net and just attach to a _supernodos_, while _supernodos_ do route. In _supernodos_ usually a Mikrotik routerboard is used as router while externals wify AP are configured as plain WDS bridge, if two _supernodos_ are connected by a wify link the router of node A see the router of node B as it was directly connected with an ethernet cable.
<<ref:1, [1]>>


=== The Previous approach: qMp

QMP <<ref:2, [2]>> do facilitate the creation of roaming enabled mesh networks, it is based on OpenWRT and BMX6, qMp already supports automatic configuration and provisioning by guifi.net map _unsolclick_ <<ref:0, [Reference Needed]>> for mesh parameters adjusting but it leave the interoperability with <<ibridmodel, Ibrid Model>> to mostly to manual static configuration done by the user or in rare cases to Quagga-BMX6 module that is unreliable, resource intensive and requires manual configuration <<ref:0, [Reference Needed]>>. Moreover qMp is designed around BMX6, in a way that to add support for another routing protocol whould imply a big refactor in qMp code.


== Libre-Mesh

Libre-Mesh is an initiative undertaken by community networks members of several continents that collaborate towards a common goal: to develop a set of tools that facilitate the deployment of Free Networks on any community in the world.

Main tool is Libre-Mesh metafirmware: based on OpenWrt, eases the creation of WiFi communities, and enables existing communities to add roaming enabled network clouds to their networks.


== Batman-adv

B.A.T.M.A.N. advanced (often referenced as batman-adv) is an implementation of the B.A.T.M.A.N. routing protocol in form of a linux kernel module operating on layer 2.

== Bird

It's a program which works as a dynamic router in an Internet type network (that is, in a network running either the IPv4 or the IPv6 protocol). It also communicate with the other routers in the Internet to discover the topology of the network which allows him to find optimal (in terms of some metric) rules for forwarding of packets (which are called routing tables) and to adapt themselves to the changing conditions such as outages of network links, building of new connections and so on.


// Specify the section template avoid "References" being threated as a special section title (see User Guide 5.4.1) that cause an xmllint error
[sect1]
== References

1. [[ref:1]] Guifi.net Ibrid Model http://es.wiki.guifi.net/wiki/Modelo_h%C3%ADbrido_guifi.net (Castilian)
2. [[ref:2]] Quick Mesh Project (qMp) http://qmp.cat/ (Catalan)


// Specify the section template avoid "References" being threated as a special section title (see User Guide 5.4.1) that cause an xmllint error
[sect1]
== Glossary

- AP: In computer networking, a wireless access point (AP) is a device that allows wireless devices to connect to a wired network using Wi-Fi, or related standards. The AP usually connects to a router (via a wired network) as a standalone device, but it can also be an integral component of the router itself. An AP is differentiated from a hotspot, which is the physical space where the wireless service is provided.

- Quagga: Quagga is a network routing software suite providing implementations of Open Shortest Path First (OSPF), Routing Information Protocol (RIP), Border Gateway Protocol (BGP) and IS-IS for Unix-like platforms.

- Router: Routers are devices which forward packets between interconnected networks in order to allow hosts not connected directly to the same local area network to communicate with each other.

- Routing Daemon: A Routing Daemon is in UNIX terminology a non-interactive program running on background which does the dynamic part of Internet routing, that is it communicates with the other routers, calculates routing tables and sends them to the OS kernel which does the actual packet forwarding.

- WDS: A wireless distribution system (WDS) is a system enabling the wireless interconnection of access points in an IEEE 802.11 network. It allows a wireless network to be expanded using multiple access points without the traditional requirement for a wired backbone to link them. The notable advantage of WDS over other solutions is it preserves the MAC addresses of client frames across links between access points.
